
# add musinsky
export LC_PAPER='en_GB.UTF-8'
export LC_TIME='en_GB.UTF-8'
export LESSHISTFILE=-

alias llt='ls --time-style="+%Y-%m-%d %H:%M:%S" -lt'
alias llt_utc='TZ=UTC llt'
alias cp='cp -p'

#source /cern/root_master/bin/thisroot.sh
alias root='root --version; root -l'
#source /cern/root_v5-34-00-patches/bin/thisroot.sh
#alias root='root -l'
